[package]
name = "leoyulee/version"
description = "A module that allows usage of Semantic Verisoning 2.0 in roblox projects"
license = "MIT"
authors = ["leoyulee"]
version = "0.1.2"


registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml"]

[dependencies]

[dev-dependencies]
# Dev dependencies can be server or shared but are only needed during development.
TestEZ = "roblox/testez@0.4.1"